// import Link from 'next/link'
// import Head from 'next/head'
// import Image from 'next/image'
// import { Document, Page } from 'react-pdf'



// export default function Resume() {
//     return (
//       <div>
//         <Head>
//           <title>Jonah's Resume</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>

//         <main className='bg-white px-10'>
//           <section className='min-h-screen'>
//           <nav className='py-10 mb-12 flex justify-between'>
//           <h1 className='text-3xl py-10 flex'>Resume</h1>
//           <ul className='flex items-center'>
//             <li className='text-xl px-4 py-2 text-white bg-gradient-to-b bg-cyan-500 rounded-md'>
//               <Link href="/">Back to home</Link>
//             </li>
//           </ul>
//           </nav>

//           <div>
        

//           </div>
//           </section>
//         </main>
        
//       </div>
//     )
//   }

